on: push
jobs:
  single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run colpal/actions-for-each
        id: for-each
        uses: ./
        with:
          patterns: 'fixtures/*'
      - if: steps.for-each.outputs.paths != '["fixtures/function-a", "fixtures/function-b", "fixtures/function-c", "fixtures/run-a", "fixtures/run-b"]'
        run: exit 1
