on: push
jobs:
  single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run colpal/actions-for-each
        id: for-each
        uses: ./
        with:
          patterns: 'fixtures/*'
      - run: echo $OUTPUT
        env:
          OUTPUT: ${{ steps.for-each.outputs.paths }}
      - if: steps.for-each.outputs.paths != '["fixtures/function-a/","fixtures/function-b/","fixtures/function-c/","fixtures/run-a/","fixtures/run-b/"]'
        run: exit 1

  multiple-folders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run colpal/actions-for-each
        id: for-each
        uses: ./
        with:
          patterns: |
            fixtures/*
            !fixtures/*-b
      - run: echo $OUTPUT
        env:
          OUTPUT: ${{ steps.for-each.outputs.paths }}
      - if: steps.for-each.outputs.paths != '["fixtures/function-a/","fixtures/function-c/","fixtures/run-a/"]'
        run: exit 1
